[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14
#[font.bold]
#family = "0xProto Nerd Font Mono"
#style = "Bold"

#[font.bold_italic]
#family = "DejaVu Serif, Regular Italic"
#style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

#[font.italic]
#family = "DejaVu Serif, Regular Italic"
#style = "Italic"

#[font.normal]
#family = "0xProto Nerd Font"
#style = "Medium"

[font.offset]
x = 0
y = 0

[general]
#import = ["/nix/store/v08ad4lbgv4x61lk6yf7yqd6z956assr-kanagawa_dragon"]
#working_directory = "/home/nixos"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "Space"
mode = "Vi"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[mouse]
hide_when_typing = true
[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "wsl"
args = ["-d", "NixOS", "--cd ~"]

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 2
y = 2
