name: ❄️ Nix test ❄️

on:
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install nix action
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix
        uses: cachix/cachix-action@v16
        with:
          name: iliyankostov9-nixos-wsl
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run tests
        run: |
          nix flake check -L

      - name: Run tests
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
